# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20171210_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='Date',
            field=models.DateField(help_text='Day of the event', verbose_name='Day of the event'),
        ),
    ]
